---
title: "Epistemic AI - EU Horizon 2020 Project"
excerpt: "<img width='500' src='/images/1647528661968.png'><br/> Although artificial intelligence (AI) has improved remarkably over the last years, 
its inability to deal with fundamental uncertainty severely limits its application. This proposal re-imagines AI with a proper treatment of 
the uncertainty stemming from our forcibly partial knowledge of the world. As currently practiced, AI cannot confidently make predictions robust 
enough to stand the test of data generated by processes different (even by tiny details, as shown by ‘adversarial’ results able to 
fool deep neural networks) from those studied at training time. While recognising this issue under different names (e.g. ‘overfitting’), 
traditional machine learning seems unable to address it in nonincremental ways. As a result, AI systems suffer from brittle behaviour, 
and find difficult to operate in new situations, e.g. adapting to driving in heavy rain or to other road users’ different styles of driving, 
e.g. deriving from cultural traits. Epistemic AI’s overall objective is to create a new paradigm for a next-generation artificial intelligence 
providing worst-case guarantees on its predictions thanks to a proper modelling of real-world uncertainties.[More information...](https://www.epistemic-ai.eu)"
collection: portfolio
---

<img width="700" src='/images/1647528661968.png'><br/> 
Epistemic AI breaks entirely with the current state of artificial intelligence and with the most exciting ongoing efforts, such as continual 
learning (making the learning process a life-long endeavour), multi-task learning (aiming to distil knowledge from multiple tasks to solve a 
different problem) or meta-learning (learning to learn). As these are all still firmly rooted in AI’s conventional principles, they fail to 
recognise the foundational issue that the discipline has with the representation of uncertain knowledge.

Our proposal goes beyond ‘human-centric’ AI, the push to make artificial constructs more trustable by human beings and more capable of 
understanding humans, since it strives to model the uncertainty stemming not just from human behaviour, but from all sources of uncertainty 
present in complex environments.

Epistemic AI’s overall objective is to create a new paradigm for a next-generation artificial intelligence providing worst-case guarantees 
on its predictions, thanks to a proper modelling of real-world uncertainties. Firstly, a new mathematical framework for optimisation under 
epistemic uncertainty will be formulated, superseding existing probabilistic approaches. The new optimisation framework will lay the premises 
for the creation of new ‘epistemic’ learning paradigms. In Epistemic AI we will focus, in particular, on some of the most important areas of 
machine learning: unsupervised learning, supervised learning and reinforcement learning.

Last but not least, the goal of the project is to foster an ecosystem of academic, research, industry and societal partners throughout Europe 
able to drive and sustain the EU’s leadership ambition in the search for a next-generation AI. <br/> 
